/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JPanel;
import model.Forestilling;

/**
 *
 * @author Morten Ricki Rasmussen
 */
public class FilmUdvalgPanel extends javax.swing.JPanel {
    private JPanel bestilBilleterPanel;

    /**
     * Creates new form Filmududvalg
     * @param forestilling
     * @param bestilBilleterPanel
     */
    public FilmUdvalgPanel(Forestilling forestilling, JPanel bestilBilleterPanel) {
        initComponents();
        titelLabel.setText(forestilling.getFilmTitel());
        datoLabel.setText("" + forestilling.getDato());
        tidspunktLabel.setText(forestilling.getTidspunkt());
        salLabel.setText(forestilling.getSalNavn());
        this.bestilBilleterPanel = bestilBilleterPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titelLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        datoLabel = new javax.swing.JLabel();
        tidspunktLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bestilBilleterButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        salLabel = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rescources/Hunger games.jpg"))); // NOI18N

        titelLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titelLabel.setText("The Hunger Games: The MockingJay 2. del");

        jLabel3.setText("Dato:");

        datoLabel.setText("2015-12-31");

        tidspunktLabel.setText("21:30");

        jLabel6.setText("Tidspunkt");

        bestilBilleterButton.setText("Bestil Billetter");
        bestilBilleterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestilBilleterButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Sal:");

        salLabel.setText("Sal 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(titelLabel)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salLabel)
                    .addComponent(tidspunktLabel)
                    .addComponent(datoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(bestilBilleterButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(datoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titelLabel)
                    .addComponent(bestilBilleterButton)
                    .addComponent(jLabel6)
                    .addComponent(tidspunktLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(salLabel))
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bestilBilleterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestilBilleterButtonActionPerformed
        bestilBilleterPanel.setVisible(true);
    }//GEN-LAST:event_bestilBilleterButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bestilBilleterButton;
    private javax.swing.JLabel datoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel salLabel;
    private javax.swing.JLabel tidspunktLabel;
    private javax.swing.JLabel titelLabel;
    // End of variables declaration//GEN-END:variables
}
